### ISSUE TITLE
Exception: Default keymaps are corrupt. Restore Blender to factory defaults before enabling this addon

### ISSUE THREAD

**Issue by xan2622** [K-410/textension#2]
Also reported on the forum: 
https://blenderartists.org/t/how-would-you-show-some-love-for-the-blender-text-editor/1163857/232

---

Here is an error that I see in the console, after launching Blender: 

Blender version: **2.83 alpha daily build (blender-2.83-31aefdeec5a6-windows64)**
Addon version: **1.0.0 (26th february 2020)**

> Traceback (most recent call last):
>   File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\textension-master\utils.py", line 224, in <lambda>
>     register(lambda: func(*args, **kwargs), first_interval=delay)
>   File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\textension-master\__init__.py", line 2289, in register
>     return keymaps_ensure(register, keymaps)
>   File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\textension-master\utils.py", line 134, in keymaps_ensure
>     raise Exception("Default keymaps are corrupt. Restore Blender to "
> Exception: Default keymaps are corrupt. Restore Blender to factory defaults before enabling this addon

---

And when I use Blender 2.82:

Blender version: **2.82 Official**
Addon version: **1.0.0 (6th march 2020)**

> Traceback (most recent call last):
>   File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\textension-master\utils.py", line 234, in <lambda>
>     register(lambda: func(*args, **kwargs), first_interval=delay)
>   File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\textension-master\__init__.py", line 2289, in register
>     return keymaps_ensure(register, keymaps)
>   File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\textension-master\utils.py", line 130, in keymaps_ensure
>     raise Exception("Default keymaps are corrupt. Restore Blender to "
> Exception: Default keymaps are corrupt. Restore Blender to factory defaults before enabling this addon

**Comment by K-410** [comment]
Thanks for the report! I can't seem to reproduce it.

The error itself happens when the addon fails (after 10 times), trying to access the active keymap configuration.

Which means:
A: Blender fails to load the keyconfig within 2 seconds after the addon is activated, which is a __very long__ time.
B: The keymaps are in fact corrupt. Something has removed the default keymaps and the addon can't find them.

Does the error appear when you enable it in preferences? Or does it only happen when the addon is already enabled when restarting blender?

Try starting blender in factory default mode ``blender --factory-startup``, then enable the addon. If this works, some other addon is doing things it shouldn't.

The reason the addon checks for keymaps is because it templates off the default keymaps when an addon keymap doesn't exist. It's also needed in order to mute default keymaps to prevent conflicts.

Could you please test and see if this version works? If not, can you paste the messages it shows in the console?

[textension.zip](https://github.com/K-410/textension/files/4302088/textension.zip)

**Comment by xan2622** [comment]
On a fresh Blender 2.82 installation (no addon installed), but after importing my custom hotkeys .py file:

<img width="674" alt="1" src="https://user-images.githubusercontent.com/1732773/76150776-67c8a480-60ae-11ea-846e-75da00acab5e.PNG">

Then, I installed your addon and as soon as I tried to activate the Textension addon: 

<img width="958" alt="2" src="https://user-images.githubusercontent.com/1732773/76150815-9c3c6080-60ae-11ea-9dbd-23ae1215057a.PNG">

Then, I saved my Blender Preferences, and quitted Blender.

After relaunching Blender, here are the lines that appeared instantly: 

<img width="958" alt="3" src="https://user-images.githubusercontent.com/1732773/76150891-369ca400-60af-11ea-9d81-7055a47d3a3e.PNG">

At this point, I wanted to retry with a very clean Blender 2.82 installation (so no other addon and no custom hotkeys imported, a real clean installation). To do that, I clicked Defaults > Load Factory Settings. And here is what I saw:

<img width="958" alt="4" src="https://user-images.githubusercontent.com/1732773/76151050-becf7900-60b0-11ea-9185-3fa404d35192.PNG">

Then I quitted Blender and relaunched it:

<img width="958" alt="5" src="https://user-images.githubusercontent.com/1732773/76151127-d8bd8b80-60b1-11ea-9e2a-5a98f8337270.PNG">


So there seems to be a problem with my hotkeys.py file or something like that.

**Comment by K-410** [comment]
Did you try the zip file I attached in the previous post?
You might need to navigate to the installed addon location and replace the files.

The files in the zip has two workarounds I'm interested in seeing:
1. Increase the retry count to 30, so it will fail only after 6 seconds.
2. Try to use default keymap config as fallback.

It will print information in the console on activation.

**Comment by xan2622** [comment]
Here is what appears with this addon (the one from your previous post on Github, above) when I activate it:

<img width="1120" alt="1" src="https://user-images.githubusercontent.com/1732773/76151371-90539d00-60b4-11ea-83be-037509ab0b04.PNG">

**Comment by K-410** [comment]
Looks like you put it in the addons root folder. It should be inside `addons\textension` or `addons\textension-master` if you downloaded the zip straight off github.

But besides that, it seems to load just fine.

I'll commit the changes.
