### ISSUE TITLE
some new features that could be usefull

### ISSUE THREAD

**Issue by JoseConseco** [K-410/textension#3]
ctrl + D - duplicate current line and paste below
shift+alt + Up Arrow / Down arrow - move current line up or down :
![2020-03-11_15-14-13](https://user-images.githubusercontent.com/13521338/76426231-115bae80-63ab-11ea-8391-38af70f46f43.gif)

**Comment by K-410** [comment]
Thanks for the suggestions.

I think those already exist by default, except for Move Line(s) which uses `Ctrl + Shift` instead of `Shift + Alt`.

![hnsofRcLVo](https://user-images.githubusercontent.com/4129450/76429160-ef642b00-63ae-11ea-8572-f6c0d3ed47d0.png)
